### ISSUE TITLE
Opacity animation

### ISSUE THREAD

**Issue by ygurzeev** [connesc/scratchcard#4]
Hi guys, 
First of all great module thanks!

One question, how do I add animation to the foreground disappearance?

Thanks!

**Comment by connesc** [comment]
Hi!
It's been a while since I have not worked on this project, but I'm always happy to hear that it's still useful. :smiley: 

Well, IIRC, you should be able to implement a custom [`Painter`](https://github.com/connesc/scratchcard#painter-class), so that you can take full control over how the foreground canvas is drawn.

If you need more help, feel free to give more context on what you are trying to implement. I will certainly be unable to help because I'm not a canvas guru myself, but someone else could bring some hints here.

**Comment by ygurzeev** [comment]
Thanks @connesc, I'll keep drilling and let you know if I reach something :)
