### ISSUE TITLE
Plain text on revealed image

### ISSUE THREAD

**Issue by Levan777** [connesc/scratchcard#7]
Hi,

I'm trying to add a plain text to the bottom layer using relative/absolute method. It actually works but the problem I'm facing is that the text is visible while images are loading. 

`<div style="border-radius: 25px; overflow: hidden; position: relative;">
            <img src="<top_image>" style="display: none;" />
            <img src="<bottom_image>" style="visibility: hidden; width: 100%; height: auto;" />
            <div style="position: absolute; top: 30px; text-align: center;"><h3>text</h3></div>
        </div>`

Is there any way to hide this text and only show when the visibility of bottom image will be visible?

Thanks

**Comment by connesc** [comment]
Hi,

If you want your text to be covered by the scratchcard, you can group it with your image in a div, make that div hidden by default and attach the scratchcard to that div. The scratchcard constructor will then make the attached element visible when ready.

Otherwise, if you want your text be outside of the scratchcard, you can make it hidden by default, and make it visible programmatically once the scratchcard has been initialized.

I hope it answers your question. 😄

**Comment by Levan777** [comment]
I merged the text with the image using PHP GD, but thanks anyway, your answer will definitely help in the future!!
